name: Generate component palette for ska-sdp-func

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:

  run_tests:
    name: Generate component palette for ska-sdp-func
    runs-on: ubuntu-20.04
    env:
      PROJECT_NAME: ska-sdp-func
      GIT_REPO: https://gitlab.com/ska-telescope/sdp/ska-sdp-func.git
      GITHUB_USERNAME: eagle.updater
      PALETTE_FILENAME: ska-sdp-func.palette

    steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen xsltproc

      - name: Fetch xml2palette from DALiuGE repo
        run: |
          wget https://raw.githubusercontent.com/ICRAR/daliuge/master/tools/xml2palette/xml2palette.py

      - name: Clone repository
        run: |
          git clone --depth 1 $GIT_REPO
          cd $PROJECT_NAME
          echo "PROJECT_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          cd ..

      - name: Create palettes
        run: |
          python3 xml2palette.py -i $PROJECT_NAME -s -o $PALETTE_FILENAME

      - name: Commit palettes to EAGLE
        env:
          EAGLE_UPDATER_TOKEN: ${{ secrets.EAGLE_UPDATER_TOKEN }}
        run: |
          git clone https://$EAGLE_UPDATER_TOKEN@github.com/ICRAR/EAGLE_test_repo
          mkdir -p EAGLE_test_repo/$PROJECT_NAME
          mv $PALETTE_FILENAME EAGLE_test_repo/$PROJECT_NAME/
          cd EAGLE_test_repo
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@gmail.com
          git add *
          git diff-index --quiet HEAD || git commit -m "Automatically generated $PROJECT_NAME palette (branch master, commit $PROJECT_VERSION)"
          git push
