name: Generate component palette for rascil.processing_components

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'

jobs:

  run_tests:
    name: Generate component palette for rascil.processing_components
    runs-on: ubuntu-20.04
    env:
      PROJECT_NAME: rascil.processing_components
      GIT_REPO: https://gitlab.com/ska-telescope/external/rascil.git
      GIT_DIRECTORY: rascil
      GITHUB_USERNAME: eagle.updater
      PALETTE_DIRECTORY: rascil
      PALETTE_FILENAME: rascil.processing_components.palette

    steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y doxygen xsltproc

      - name: Fetch xml2palette from DALiuGE repo
        run: |
          wget https://raw.githubusercontent.com/ICRAR/daliuge/master/tools/xml2palette/xml2palette.py

      - name: Clone repository
        run: |
          git clone --depth 1 $GIT_REPO
          cd $GIT_DIRECTORY
          echo "PROJECT_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "PROJECT_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
          cd ..

      - name: Create palette
        run: |
          python3 xml2palette.py -s -r -m rascil.processing_components $GIT_DIRECTORY $PALETTE_FILENAME

      - name: Commit palette to EAGLE_test_repo
        env:
          EAGLE_UPDATER_TOKEN: ${{ secrets.EAGLE_UPDATER_TOKEN }}
        run: |
          git clone https://$EAGLE_UPDATER_TOKEN@github.com/ICRAR/EAGLE_test_repo
          mkdir -p EAGLE_test_repo/$PALETTE_DIRECTORY
          mv $PALETTE_FILENAME EAGLE_test_repo/$PALETTE_DIRECTORY/
          cd EAGLE_test_repo
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@gmail.com
          git add *
          git diff-index --quiet HEAD || git commit -m "Automatically generated $PROJECT_NAME palette (branch $PROJECT_BRANCH, commit $PROJECT_VERSION)"
          git push

#      - name: Commit palette to ska-sdp-daliuge-graphs
#        env:
#          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
#        run: |
#          git clone https://james-strauss-uwa:GITLAB_TOKEN@gitlab.com/ska-telescope/ska-sdp-daliuge-graphs.git "$GITHUB_SHA"
#          mkdir -p $GITHUB_SHA/palettes/$PALETTE_DIRECTORY
#          mv $PALETTE_FILENAME $GITHUB_SHA/palettes/$PALETTE_DIRECTORY/
#          cd $GITHUB_SHA
#          git config --global user.name james-strauss-uwa
#          git config --global user.email james.strauss@uwa.edu.au
#          git add *
#          git diff-index --quiet HEAD || git commit -m "Automatically generated $PROJECT_NAME palette (branch $PROJECT_BRANCH, commit $PROJECT_VERSION)"
#          git push
